@TenantSpecific_HostAddress = http://localhost:5293

GET {{TenantSpecific_HostAddress}}/weatherforecast/
Accept: application/json
x-tenant-id: 100

###

GET {{TenantSpecific_HostAddress}}/weatherforecast/
Accept: application/json
x-tenant-id: 200

###

GET {{TenantSpecific_HostAddress}}/weatherforecast/
Accept: application/json
x-tenant-id: 300